language: java
jdk: oraclejdk8
cache:
    apt: true
    directories:
        - $HOME/.m2
script: ./scripts/keep_alive.sh
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# after_success:
#   - mvn clean install jacoco:report coveralls:report
notifications:
    slack: cunyponder:A8GuEoj0voEn2H7MJDL1eNji
